using Runiq.AI.Cli.Models;

namespace Runiq.AI.Cli.Planning;

public sealed class ProjectPlanner
{
    public ProjectPlan CreatePlan(ProjectDefinition definition)
    {
        var root = definition.Name;
        var apiProjectRoot = Path.Combine(root, "src", $"{definition.Name}.Api");
        var directories = new List<DirectoryPlan>
        {
            new() { Path = root },
            new() { Path = Path.Combine(root, "src") },
            new() { Path = apiProjectRoot },
            new() { Path = Path.Combine(apiProjectRoot, "Agents") },
            new() { Path = Path.Combine(apiProjectRoot, "Tools") },
            new() { Path = Path.Combine(apiProjectRoot, "Flows") },
            new() { Path = Path.Combine(root, "tests") }
        };

        if (definition.EnableMcp)
        {
            directories.Add(new DirectoryPlan { Path = Path.Combine(apiProjectRoot, "Mcp") });
        }

        return new ProjectPlan
        {
            Directories = directories,
            Files =
            [
                new FilePlan
                {
                    Path = Path.Combine(root, "README.md"),
                    Content = $"""
                    # {definition.Name}

                    Generated by Runiq CLI.

                    ## Try These Prompts

                    Open the Runiq Dashboard and try:

                    ```text
                    Create a practical one-day historical trip plan in Istanbul for two people. Keep it easy to walk.
                    ```

                    More examples:

                    ```text
                    Plan the same trip for Izmir and account for the weather.
                    ```

                    ```text
                    Which agents and tools contributed to the result?
                    ```

                    ```text
                    Show the workflow trace for the Istanbul plan.
                    ```
                    """
                }
            ]
        };
    }
}

